environment-type needs ot be lower case

diff --git a/.github/workflows/input-validation-test.yaml b/.github/workflows/input-validation-test.yaml
--- a/.github/workflows/input-validation-test.yaml
+++ b/.github/workflows/input-validation-test.yaml
@@ -45,9 +45,9 @@ jobs:
             exit 1
           fi
 
-          if [[ ! "${{inputs.vend_workload_tags}}" =~ ^Department:[a-zA-Z_0-9:\ ]+,Team:[a-zA-Z0-9_-+:\ \/()]+,Support:[a-zA-Z]+,DataClassification:[a-zA-Z]+$ ]]; then
-              echo "Error: vend_workload_tags does not match the required format."
-              exit 1
+          if [[ ! "${{ inputs.vend_workload_tags }}" =~ ^Department:[\&a-zA-Z_0-9\ ]+,Team:[a-zA-Z0-9_+-:\ \/()]+,Support:[a-zA-Z]+,DataClassification:[a-zA-Z]+$ ]]; then
+            echo "Error: vend_workload_tags does not match the required format."
+            exit 1
           fi
 
   do-stuff:
