rename pat token secret in github workflows

diff --git a/.github/workflows/input-validation-test.yaml b/.github/workflows/input-validation-test.yaml
--- a/.github/workflows/input-validation-test.yaml
+++ b/.github/workflows/input-validation-test.yaml
@@ -43,3 +43,8 @@ jobs:
             echo "Error: vend_instance must be between 0 and 10 lower case characters or numbers, and contain no spaces."
             exit 1
           fi
+
+          if [[ ! "${{ inputs.vend_workload_tags }}" =~ ^Department:[a-zA-Z_0-9]+,Team:[a-z A-Z_0-9]+,Support:[a-zA-Z]+,DataClassification:[a-zA-Z]+$ ]]; then
+            echo "Error: vend_workload_tags does not match the required format."
+            exit 1
+          fi
